param(
    [string]$RepositoryName = 'biovault-biobank-database-project',
    [string]$Description = 'Complete PostgreSQL biobank database project with ERD, 3NF report, tests, presentation, video, and CRUD desktop application.'
)

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $projectRoot

# The repository may have been generated by an isolated build account. Scope
# Git's ownership exception to this process and this exact repository only.
$env:GIT_CONFIG_COUNT = '1'
$env:GIT_CONFIG_KEY_0 = 'safe.directory'
$env:GIT_CONFIG_VALUE_0 = $projectRoot.Replace('\', '/')

if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    throw 'GitHub CLI (gh) is not installed. Install it from https://cli.github.com/'
}

& gh auth status -h github.com
if ($LASTEXITCODE -ne 0) {
    Write-Host ''
    Write-Host 'GitHub authentication is required. Run:' -ForegroundColor Yellow
    Write-Host '  gh auth login -h github.com -p https -w' -ForegroundColor Cyan
    Write-Host 'Then rerun this script.' -ForegroundColor Yellow
    exit 1
}

$dirty = & git status --porcelain
if ($dirty) {
    throw 'The worktree is not clean. Commit or review local changes before publishing.'
}

$remotes = @(& git remote)
if ($remotes -contains 'origin') {
    $existingOrigin = (& git remote get-url origin).Trim()
    throw "A remote named origin already exists: $existingOrigin"
}

$login = (& gh api user --jq .login).Trim()
$fullName = "$login/$RepositoryName"

$savedErrorPreference = $ErrorActionPreference
$ErrorActionPreference = 'SilentlyContinue'
$null = & gh repo view $fullName --json nameWithOwner 2>$null
$repositoryAlreadyExists = $LASTEXITCODE -eq 0
$ErrorActionPreference = $savedErrorPreference

if ($repositoryAlreadyExists) {
    throw "Repository $fullName already exists. Choose another -RepositoryName."
}

& gh repo create $RepositoryName `
    --public `
    --description $Description `
    --source . `
    --remote origin `
    --push

if ($LASTEXITCODE -ne 0) {
    throw 'GitHub repository creation or push failed.'
}

$url = (& gh repo view --json url --jq .url).Trim()
Write-Host ''
Write-Host "Published successfully: $url" -ForegroundColor Green
